[build]
nixpacksVersion = "1.16.0"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
aptPkgs = ["bun"]

[phases.build]
cmds = [
  "bun install",
  "bun run build"
]

[phases.deploy]
startCommand = "bun run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
